# Generated by Django 3.2.9 on 2022-01-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20220122_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.ManyToManyField(related_name='choices', to='polls.Choice'),
        ),
    ]
