# Generated by Django 3.2.9 on 2022-01-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20220122_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='uuid',
            field=models.CharField(max_length=16, null=True, verbose_name='Идентификатор'),
        ),
        migrations.AddField(
            model_name='question',
            name='uuid',
            field=models.CharField(max_length=16, null=True, verbose_name='Идентификатор'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='uuid',
            field=models.CharField(max_length=16, null=True, verbose_name='Идентификатор'),
        ),
    ]
