# Generated by Django 3.2.9 on 2022-01-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20220123_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.ManyToManyField(related_name='question_choices', to='polls.Choice', verbose_name='Варианты ответа'),
        ),
    ]
